### ISSUE TITLE
Crear boton 'reset', 'feedback' y 'path'.

### ISSUE THREAD

**Issue by Yefri97** [catalinacst/game#12]
1. **reset:** reseteara los objetos y los intereses.

2. **feedback:** enviara a un form de google.

3. **path:** agregar modal para la imagen.

**Comment by Yefri97** [comment]
Ya fueron creados los metodos en el controlador, solo falta linkearlos con los botones.

**Comment by catalinacst** [comment]
Falta vincular el botón Path y Feedback.

**Comment by catalinacst** [comment]
Los botones están creados y en el proyecto.
